apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-configs
data:
  db_name: flask-db
  user: flask-user
  port: "5432" # Same should be configured in flask app config/Env variables
  host: postgres-service # We are using psql service name as a host, it'll be used only for flask connection

