apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80
      env:
        - name: DB_NAME
          value: "123"
      resources:
        requests:
          cpu: "125m"
          memory: "64Mi"
        limits:
          cpu: "250m"
          memory: "128Mi"
      volumeMounts:
        - mountPath: /app/FlaskApp/
          name: psql-pv-storage
        - name: flask-configs-vol
          mountPath: /app/FlaskApp/app.ini
          subPath: app.ini
        - name: flask-configs-vol
          mountPath: /app/FlaskApp/app1.ini
          subPath: app1.ini
  volumes:
    - name: psql-pv-storage
      persistentVolumeClaim:
        claimName: psql-pv-claim
    - name: flask-configs-vol
      configMap:
        name: flask-configs
      # volumeMounts:
      #   - name: config-vol
      #     mountPath: /etc/my-config/app.ini
      #     subPath: app.ini
  # volumes:
  #   - name: config-vol
  #     configMap:
  #       name: flask-configs
        
