apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-psql-pv
spec:
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: "name-for-nodeaffivity"
  #             operator: In
  #             values:
  #               - myNodeAffivity
