apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-configs
data:
  app.ini: |
    [SupportedPlatforms]
    platforms = [Linux, Windows, Ubuntu]

    [Server]
    use_env_variables = False
    host = 0.0.0.0
    port = 5052
    ;Debug must be set to False in Production environment
    debug = False
    use_reloader = False

    [Log]
    logs_enabled = True
    log_level = DEBUG
  app1.ini: |
    [SupportedPlatforms]
    platforms = [Linux, Windows]

    [Server]
    use_env_variables = False
    host = 0.0.0.0
    port = 5052
    ;Debug must be set to False in Production environment
    debug = False
    use_reloader = False

    [Log]
    logs_enabled = True
    log_level = DEBUG
  